// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ApprovalData } from "./../tables/Approval.sol";

interface IApprovalSystem {
  function setApproval(address grantor, address grantee, uint256 systemID, ApprovalData memory approval) external;

  function setApproval(address grantee, ApprovalData memory approval) external;

  function revokeApproval(address grantee, uint256 systemID) external;

  function revokeApproval(address grantee) external;

  function reduceApproval(address grantor, address grantee, bytes memory funcSelectorAndArgs) external;

  function reduceApproval(
    address grantor,
    address grantee,
    uint256 systemID,
    bytes memory funcSelectorAndArgs
  ) external;
}
