// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IModule } from "./IModule.sol";

interface IModuleInstallationSystem {
  function installModule(bytes16 namespace, IModule module, bytes memory args) external;
}
