// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("Approval")));
bytes32 constant ApprovalTableId = _tableId;

struct ApprovalData {
  uint128 expiryTimestamp;
  uint128 numCalls;
  bytes funcSelectorAndArgs;
}

library Approval {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](3);
    _schema[0] = SchemaType.UINT128;
    _schema[1] = SchemaType.UINT128;
    _schema[2] = SchemaType.BYTES;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](3);
    _fieldNames[0] = "expiryTimestamp";
    _fieldNames[1] = "numCalls";
    _fieldNames[2] = "funcSelectorAndArgs";
    return ("Approval", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get expiryTimestamp */
  function getExpiryTimestamp(bytes32 approvalSelector) internal view returns (uint128 expiryTimestamp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint128(Bytes.slice16(_blob, 0)));
  }

  /** Get expiryTimestamp (using the specified store) */
  function getExpiryTimestamp(IStore _store, bytes32 approvalSelector) internal view returns (uint128 expiryTimestamp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint128(Bytes.slice16(_blob, 0)));
  }

  /** Set expiryTimestamp */
  function setExpiryTimestamp(bytes32 approvalSelector, uint128 expiryTimestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((expiryTimestamp)));
  }

  /** Set expiryTimestamp (using the specified store) */
  function setExpiryTimestamp(IStore _store, bytes32 approvalSelector, uint128 expiryTimestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((expiryTimestamp)));
  }

  /** Get numCalls */
  function getNumCalls(bytes32 approvalSelector) internal view returns (uint128 numCalls) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint128(Bytes.slice16(_blob, 0)));
  }

  /** Get numCalls (using the specified store) */
  function getNumCalls(IStore _store, bytes32 approvalSelector) internal view returns (uint128 numCalls) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint128(Bytes.slice16(_blob, 0)));
  }

  /** Set numCalls */
  function setNumCalls(bytes32 approvalSelector, uint128 numCalls) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((numCalls)));
  }

  /** Set numCalls (using the specified store) */
  function setNumCalls(IStore _store, bytes32 approvalSelector, uint128 numCalls) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((numCalls)));
  }

  /** Get funcSelectorAndArgs */
  function getFuncSelectorAndArgs(bytes32 approvalSelector) internal view returns (bytes memory funcSelectorAndArgs) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (bytes(_blob));
  }

  /** Get funcSelectorAndArgs (using the specified store) */
  function getFuncSelectorAndArgs(
    IStore _store,
    bytes32 approvalSelector
  ) internal view returns (bytes memory funcSelectorAndArgs) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (bytes(_blob));
  }

  /** Set funcSelectorAndArgs */
  function setFuncSelectorAndArgs(bytes32 approvalSelector, bytes memory funcSelectorAndArgs) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    StoreSwitch.setField(_tableId, _keyTuple, 2, bytes((funcSelectorAndArgs)));
  }

  /** Set funcSelectorAndArgs (using the specified store) */
  function setFuncSelectorAndArgs(IStore _store, bytes32 approvalSelector, bytes memory funcSelectorAndArgs) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    _store.setField(_tableId, _keyTuple, 2, bytes((funcSelectorAndArgs)));
  }

  /** Get the length of funcSelectorAndArgs */
  function lengthFuncSelectorAndArgs(bytes32 approvalSelector) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 2, getSchema());
    return _byteLength / 1;
  }

  /** Get the length of funcSelectorAndArgs (using the specified store) */
  function lengthFuncSelectorAndArgs(IStore _store, bytes32 approvalSelector) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 2, getSchema());
    return _byteLength / 1;
  }

  /** Get an item of funcSelectorAndArgs (unchecked, returns invalid data if index overflows) */
  function getItemFuncSelectorAndArgs(bytes32 approvalSelector, uint256 _index) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 2, getSchema(), _index * 1, (_index + 1) * 1);
    return (bytes(_blob));
  }

  /** Get an item of funcSelectorAndArgs (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemFuncSelectorAndArgs(
    IStore _store,
    bytes32 approvalSelector,
    uint256 _index
  ) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 2, getSchema(), _index * 1, (_index + 1) * 1);
    return (bytes(_blob));
  }

  /** Push a slice to funcSelectorAndArgs */
  function pushFuncSelectorAndArgs(bytes32 approvalSelector, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    StoreSwitch.pushToField(_tableId, _keyTuple, 2, bytes((_slice)));
  }

  /** Push a slice to funcSelectorAndArgs (using the specified store) */
  function pushFuncSelectorAndArgs(IStore _store, bytes32 approvalSelector, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    _store.pushToField(_tableId, _keyTuple, 2, bytes((_slice)));
  }

  /** Pop a slice from funcSelectorAndArgs */
  function popFuncSelectorAndArgs(bytes32 approvalSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    StoreSwitch.popFromField(_tableId, _keyTuple, 2, 1);
  }

  /** Pop a slice from funcSelectorAndArgs (using the specified store) */
  function popFuncSelectorAndArgs(IStore _store, bytes32 approvalSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    _store.popFromField(_tableId, _keyTuple, 2, 1);
  }

  /** Update a slice of funcSelectorAndArgs at `_index` */
  function updateFuncSelectorAndArgs(bytes32 approvalSelector, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    StoreSwitch.updateInField(_tableId, _keyTuple, 2, _index * 1, bytes((_slice)));
  }

  /** Update a slice of funcSelectorAndArgs (using the specified store) at `_index` */
  function updateFuncSelectorAndArgs(
    IStore _store,
    bytes32 approvalSelector,
    uint256 _index,
    bytes memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    _store.updateInField(_tableId, _keyTuple, 2, _index * 1, bytes((_slice)));
  }

  /** Get the full data */
  function get(bytes32 approvalSelector) internal view returns (ApprovalData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 approvalSelector) internal view returns (ApprovalData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 approvalSelector,
    uint128 expiryTimestamp,
    uint128 numCalls,
    bytes memory funcSelectorAndArgs
  ) internal {
    bytes memory _data = encode(expiryTimestamp, numCalls, funcSelectorAndArgs);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 approvalSelector,
    uint128 expiryTimestamp,
    uint128 numCalls,
    bytes memory funcSelectorAndArgs
  ) internal {
    bytes memory _data = encode(expiryTimestamp, numCalls, funcSelectorAndArgs);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 approvalSelector, ApprovalData memory _table) internal {
    set(approvalSelector, _table.expiryTimestamp, _table.numCalls, _table.funcSelectorAndArgs);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 approvalSelector, ApprovalData memory _table) internal {
    set(_store, approvalSelector, _table.expiryTimestamp, _table.numCalls, _table.funcSelectorAndArgs);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal view returns (ApprovalData memory _table) {
    // 32 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 32));

    _table.expiryTimestamp = (uint128(Bytes.slice16(_blob, 0)));

    _table.numCalls = (uint128(Bytes.slice16(_blob, 16)));

    // Store trims the blob if dynamic fields are all empty
    if (_blob.length > 32) {
      uint256 _start;
      // skip static data length + dynamic lengths word
      uint256 _end = 64;

      _start = _end;
      _end += _encodedLengths.atIndex(0);
      _table.funcSelectorAndArgs = (bytes(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
    }
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    uint128 expiryTimestamp,
    uint128 numCalls,
    bytes memory funcSelectorAndArgs
  ) internal view returns (bytes memory) {
    uint40[] memory _counters = new uint40[](1);
    _counters[0] = uint40(bytes(funcSelectorAndArgs).length);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return abi.encodePacked(expiryTimestamp, numCalls, _encodedLengths.unwrap(), bytes((funcSelectorAndArgs)));
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 approvalSelector) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 approvalSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 approvalSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = approvalSelector;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
